#!/usr/bin/env python

import sys
import urllib2
from BeautifulSoup import BeautifulSoup

if len(sys.argv) <= 1:
    print "Usage: %s <query>" % (sys.argv[9], )
    sys.exit(1)

query = sys.argv[1]

root = "http://www.shooter.cn"
querylink = "%s/search/%s/" % (self.root, query)

soup = BeautifulSoup(urllib2.urlopen(querylink))
sublink = "%s/%s" % (root, 
        soup.find("span", {"class": "sublist_box_title_l").find("a", {"class": "introtitle"})["href"])

soup = BeautifulSoup(urllib2.urlopen(sublink))


