#!/usr/bin/env bash

this=${0##*/}
usage() {
    echo "Usage: $this <word>"
}

argc=$#
[[ $argc -ne 1 ]] && { usage ; exit 1 ; }

word=$1
target="http://dict-co.iciba.com/api/dictionary.php?w=$word"
curl -s $target | tr '<>/' '|' | while read line
do
    #echo $line
    tag=$(echo $line | awk -F '|' '{print $2}')
    content=$(echo $line | awk -F '|' '{print $3}')

    if [ "$content" ]
    then
        case $tag in
            ps)          echo [$content] ;;
            pos)         echo -n -e "\033[1m$content\033[m"|sed -e 's/\&amp;/\&/' ;;
            acceptation) echo $content ;;
        esac
    fi
done
echo
