#!/usr/bin/env bash

this=${0##*/}
usage() {
    echo "Usage: $this <word>"
}

argc=$#
[[ $argc -ne 1 ]] && { usage ; exit 1 ; }

word=$1
target="http://dict-co.iciba.com/api/dictionary.php?w=$word"
IFS=\>
curl -s $target | while read -d \< tag content
do
    case $tag in
        ps)          echo -n [$content] ;;
        pos)         echo ; echo -n -e "\033[1m$content\033[m"|sed -e 's/\&amp;/\&/' ;;
        acceptation) echo ; echo -n $content ;;
    esac
done
unset IFS
